---
title: "Codebook"
author: "Cedric Dungo"
date: "12/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Variable definitions

* **features <- features.txt** : 561 rows, 2 columns  
*The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ.*
* **activities <- activity_labels.txt** : 6 rows, 2 columns  
*List of activities performed when the corresponding measurements were taken and its codes (labels)*
* **subject_test <- test/subject_test.txt** : 2947 rows, 1 column  
*Contains test data of 9/30 volunteer test subjects being observed*
* **x_test <- test/X_test.txt** : 2947 rows, 561 columns  
* *Contains recorded features test data*
* **y_test <- test/y_test.txt** : 2947 rows, 1 columns  
*Contains test data of activities’code labels*
* **subject_train <- test/subject_train.txt** : 7352 rows, 1 column  
*Contains train data of 21/30 volunteer subjects being observed*
* **x_train <- test/X_train.txt** : 7352 rows, 561 columns  
*Contains recorded features train data*
* **y_train <- test/y_train.txt** : 7352 rows, 1 columns  
*Contains train data of activities’code labels*


## Merging processes
* **X (10299 rows, 561 columns)** is created by merging **x_train** and **x_test** using **rbind()** function
* **Y (10299 rows, 1 column)** is created by merging **y_train** and **y_test** using **rbind()** function
* **Subject (10299 rows, 1 column)** is created by merging **subject_train** and **subject_test** using **rbind()** function
* **Merged_Data (10299 rows, 563 column)** is created by merging **Subject**, **Y** and **X** using **cbind()** function
* **TidyData (10299 rows, 88 columns)** is created by subsetting Merged_Data, selecting only columns: **subject**, **code** and the measurements on the **mean** and standard deviation (**std**) for each measurement

## Final Data
* **FinalData (180 rows, 88 columns)** is created by summarizing **TidyData** taking the means of each variable for each activity and each subject, after grouped by subject and activity.
Export **FinalData** into **FinalData.txt** file.
